version: "3.8"
services:
  db:
    image: library/mysql:8.0
    container_name: test-db
    restart: always
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      TZ: Asia/Seoul
