global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
#  스프링 어플리케이션 연동
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    scrape_interval: 1s # 수집 주기는 테스트를 위한 1초 단위로 설정(10초 ~ 1분)
    static_configs:
      - targets: ['localhost:8081']
