spring:
  datasource:
    url: jdbc:mysql://localhost:53306/test
    username: root
    password: root

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
